import React from "react";
import Head from "next/head";
import favicon from "../assets/logo/logo.ico";
const Layout = ({ children, pageTitle }) => {
  console.log(favicon);
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon.src} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default Layout;

// <!-- Head html -->
// <meta name="viewport" content="width=device-width, initial-scale=1">
// <meta http-equiv="X-UA-Compatible" content="IE=edge">
// <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
// <link rel="apple-touch-icon" href="icon.png">

// <meta name="description" content="Starter kit of custom HTML & CSS project with Webpack 4.">
// <meta name="Keywords" content="Webpack, Bootstrap">
// <meta name="author" content="Crowscript"></meta>
